export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const FETCH_HOUSES_START = 'FETCH_HOUSES_START';
export const FETCH_HOUSES_SUCCESS = 'FETCH_HOUSES_SUCCESS';
export const FETCH_HOUSES_FAIL = 'FETCH_HOUSES_FAIL';

export const FILTER_HOUSES_START = 'FILTER_HOUSES_START';
export const FILTER_HOUSES_SUCCESS = 'FILTER_HOUSES_SUCCESS';
export const FILTER_HOUSES_FAIL = 'FILTER_HOUSES_FAIL';

export const GET_HOUSE_START = 'GET_HOUSE_START';
export const GET_HOUSE_SUCCESS = 'GET_HOUSE_SUCCESS';
export const GET_HOUSE_FAIL = 'GET_HOUSE_FAIL';

export const GET_MY_HOUSES_START = 'GET_MY_HOUSES_START';
export const GET_MY_HOUSES_SUCCESS = 'GET_MY_HOUSES_SUCCESS';
export const GET_MY_HOUSES_FAIL = 'GET_MY_HOUSES_FAIL';

export const DELETE_MY_HOUSE = 'DELETE_MY_HOUSE';
export const UPDATE_MY_HOUSE = 'UPDATE_MY_HOUSE';
export const ADD_MY_HOUSE = 'ADD_MY_HOUSE';

export const RESERVATION_HOUSES_START = 'RESERVATION_HOUSES_START';
export const RESERVATION_HOUSES_SUCCESS = 'RESERVATION_HOUSES_SUCCESS';
export const RESERVATION_HOUSES_FAIL = 'RESERVATION_HOUSES_FAIL';

export const GET_RESERVATION_HOUSES_START = 'GET_RESERVATION_HOUSES_START';
export const GET_RESERVATION_HOUSES_SUCCESS = 'GET_RESERVATION_HOUSES_SUCCESS';
export const GET_RESERVATION_HOUSES_FAIL = 'GET_RESERVATION_HOUSES_FAIL';

export const RESERVATION_HOUSES_HANDLER = 'RESERVATION_HOUSES_HANDLER';

export const GET_RESERVATION_HOUSE = 'GET_RESERVATION_HOUSE';